import "./styles/globals.scss";
// import { Inter } from "next/font/google";

export const metadata = {
  title: "My Portfolio",
  description: "Generated by Akash Sarker",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
